### ISSUE TITLE
Overly-tight pins on referencing

### ISSUE THREAD

**Issue by bollwyvl** [p1c2u/jsonschema-spec#24]
Congratulations on the 0.2.0 release! :tada:

One concern noted [downstream](https://github.com/conda-forge/jsonschema-spec-feedstock/pull/6), the `^` specifiers act unpredictably, generating the following metadata in the wheel:

```
Requires-Dist: referencing (>=0.24.4,<0.25.0)
```

This may not have been the intended tightness of the spec, as the upstream package is already on `0.29.0`, and likely includes bug fixes, features, compatibility with its rust-based upstream, and performance benefits... and it seems unlikely that features would have been taken away already for such a relatively new package.

This is _not_ such a big issue with e.g. `jsonschema-specifications`, as the `^` works differently for non-`0.*` versions, and is probably closer to what is intended.

```
Requires-Dist: jsonschema-specifications (>=2023.3.4,<2024.0.0)
```

**Comment by p1c2u** [comment]
Hi @bollwyvl 

Indeed that was not intended 🙄  Thanks for catching this issue.

**Comment by mgorny** [comment]
Thank you.
